### ISSUE TITLE
compatibility with css-in-js projects?

### ISSUE THREAD

**Issue by serapath** [ausi/cq-prolyfill#10]
see https://github.com/MicheleBertoli/css-in-js

I'm following `element queries` and `container queries` for quite some time now and think they will be part of the future for sure. Meanwhile, i also think the future of css will be js in one way or another, so i wonder if it's possible to use a container query **ponyfill** :-) with for example [jss](https://github.com/jsstyles/jss), and especially because in jss or in general through javascript, all CSS Stylesheets can be updated during runtime by interacting with `document.styleSheets`

**Comment by ausi** [comment]
Adding style or link elements to the head should be detected automatically by cq-prolyfill, but if you’re using JavaScript to modify a stylesheet you should call the API method [`reprocess()`](https://github.com/ausi/cq-prolyfill/blob/master/docs/api.md#reprocessfn-callback) afterwards to let cq-prolyfill know that some styles may have changed. So using jss together with cq-prolyfill should work fine.

**Comment by serapath** [comment]
thx :-)
