### ISSUE TITLE
Skip to offset parent in getContainer

### ISSUE THREAD

**Issue by ausi** [ausi/cq-prolyfill#12]
`getContainer()` should skip parent nodes of `position: absolute` elements until it finds a “positioned” parent. For `position: fixed` it should skip directly to the viewport.

**Comment by rjgotten** [comment]
> For `position: fixed` it should skip directly to the viewport.

No. Elements that have `position:fixed` are first positioned against the nearest ancestor that has a transform applied. They are only positioned against the viewport if there is no such ancestor.

**Comment by ausi** [comment]
You’re right. Thanks for the hint!

**Comment by ausi** [comment]
Implemented in version [0.4.0](https://github.com/ausi/cq-prolyfill/releases/tag/v0.4.0).
