### ISSUE TITLE
Inline styles with Radium

### ISSUE THREAD

**Issue by sidjain26** [ausi/cq-prolyfill#13]
How can I use this with [Radium](https://github.com/FormidableLabs/radium/)?

**Comment by ausi** [comment]
I’m not familiar with Radium, but from its documentation it looks like it works with pure inline styles and doesn’t use CSS selectors. *cq-prolyfill* relies on CSS selectors, so in my opinion you cannot use these two projects directly together.

Radium has support for a small subset of CSS selectors: `:hover`, `:focus`, `:active` and `@media`. If they implement the `:container(…)` selector, it might be possible to use it in conjunction with *cq-prolyfill*.
