### ISSUE TITLE
Element Query?

### ISSUE THREAD

**Issue by ariona** [ausi/cq-prolyfill#14]
Hello, can I use this as element query? I Just realize that this library will watch the container of asigned element, and add class to it.

But what if i want to watch the element itself, not the container? So for example i want to change the style when the width of element is on certain size.

**Comment by ausi** [comment]
Element queries and container queries are basically the same, the only difference is that with container queries you cannot style an element based on a query for itself. The reason for that is to prevent recursion. You can read more about that topic here: [au.si/css-container-queries](https://au.si/css-container-queries).

**Comment by ariona** [comment]
Well, i have read all about them, and understand how hard this concept to be implemented due to performance impact. I thought i can use this prolyfill for element-query as well. Do you have any best workaround for this or do i need another polyfill?

Thanks.

**Comment by ausi** [comment]
The best workaround would be to write the queries as container queries and adding a container in the markup if necessary. E.g. instead of this:

```html
<div class="element"></div>
<style>
.element:media(min-width: 10em) { color: red }
</style>
```

you could write it this way with container queries:

```html
<div class="element-wrap">
	<div class="element"></div>
</div>
<style>
.element:container(width >= 10em) { color: red }
</style>
```

But in most cases you wouldn’t need to add an extra element because there is already one. Can you give a concrete example of how you want to use element queries?

You can find a list of other container/element query prolyfills here: https://gist.github.com/davatron5000/bbede54cf189bf53e4de#attempts-to-polyfill

**Comment by ariona** [comment]
Here is my problem.
```html
<div class="grid-container">
  <div class="grid-item"></div>
  <div class="grid-item w2"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
</div>
```
So basically I want to change the width of `.grid-item.w2` on certain width. If i do like this:

```css
.grid-item.w2:container(width<450px){ ... }
```
Then it will check the `.grid-container` width instead of `.grid-item right`?

Well this is definitely the element-query case, and I guess I'll need another polyfill for this to work :)

**Comment by ausi** [comment]
Yes, `.grid-item.w2:container(width<450px)` would check the query against the `.grid-container`. But changing the width based on the width of the same element doesn’t really makes sense IMO. The following element query would not work correctly:

```css
.grid-item.w2:media(width < 450px) {
	width: 600px;
}
```
