### ISSUE TITLE
Sourcemaps do not work. Maybe remove "<style media="all">" in head? 

### ISSUE THREAD

**Issue by burgart** [ausi/cq-prolyfill#16]
Hello,
the source maps do not work because the styles are written directly into the head area. It would be nice if you could change this, so we are able to work with sourcemaps.

Thanks in advance,
Burgart

**Comment by ausi** [comment]
You can prevent that by [using the PostCSS plugin](https://github.com/ausi/cq-prolyfill/blob/master/docs/postcss.md). This way the styles don’t have to be rewritten on the client-side and the original `<link>` tag stays unchanged.

**Comment by ausi** [comment]
@burgart did it work for you?

**Comment by gisu** [comment]
Works now with the Sass Mixin.
