### ISSUE TITLE
Add a Sass mixin as an alternative to the PostCSS plugin

### ISSUE THREAD

**Issue by ausi** [ausi/cq-prolyfill#17]
Add a _.scss_ file to the project with a mixin that escapes the selector like https://gist.github.com/rask/434e96f603e8b439dc64 but in SCSS only if possible.

**Comment by rask** [comment]
I tried to make a pure Sass solution but ended up with that function as it was faster to implement that way (than trial and erroring to get the parsing working in Sass). I could try and see whether a pure Sass version is doable.

**Comment by ausi** [comment]
I already played around with it and got a pretty good working solution: http://pastebin.com/wke8E7gZ

The only concern I have is performance. And the color filters don’t work currently.

**Comment by rask** [comment]
Oh nice, I'll try that out and see how it works. I wonder whether there are any benchmarking tools for these.

**Comment by ausi** [comment]
Implemented in version [0.4.0](https://github.com/ausi/cq-prolyfill/releases/tag/v0.4.0).
