### ISSUE TITLE
Angular directives and getComputedStyle

### ISSUE THREAD

**Issue by TomOffringa** [ausi/cq-prolyfill#20]
I'm loving this 'prolyfill' but I'm encountering some issues with Angular directives (atleast, I'm guessing it's that). 

`Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.` 

It's line 1059 that's throwing this error. I know this isn't completely relevant for this library but I was wondering if somebody found a workaround for this. 

Best,

Tom

**Comment by ausi** [comment]
Can you provide more information on the error, like a call stack?

Is it possible to reproduce this error with a small testcase, ideally as a [JSFiddle](https://jsfiddle.net/) or similar.

Do you have a link to the affected webpage?

**Comment by TomOffringa** [comment]
Hi,

I've tried a couple of things to reproduce this in a testcase but haven't been able to. Will keep you posted.

**Comment by TomOffringa** [comment]
This seemed to be an Angular and JS error not concerning this library. Fixed it by changing the order of JS resolving.
