### ISSUE TITLE
xhr causes multiple CSS loads

### ISSUE THREAD

**Issue by TomOffringa** [ausi/cq-prolyfill#24]
Hi,

It's a bit hard to describe but my app loads multiple of the same files and I located it back to the xhr request done in the cq-prolyfill lib. I looked througout the code to see if I could locate where the problem lies but I can't pin it down exactly. Do you have any pointers where I might look for debugging and all?

It's an app written in Angular. 

Sorry for the vague description, don't really know how to explain this problem. 

Thanks!

**Comment by ausi** [comment]
You can prevent the double download of the CSS files by using the [PostCSS plugin](https://github.com/ausi/cq-prolyfill/blob/master/docs/postcss.md) or [Sass mixin](https://github.com/ausi/cq-prolyfill/issues/17#issuecomment-183756013). And you should [enable CORS](https://github.com/ausi/cq-prolyfill/blob/master/docs/cors.md) if the stylesheet is loaded from a different domain.

**Comment by TomOffringa** [comment]
I'll see and try if that works!

**Comment by TomOffringa** [comment]
We tried implementing the Sass mixin, but it still seems to load the files multiple times. So a couple of questions:

1. Do we need to implement both the Sass mixin and the gulp function or is just the Sass mixin enough (it seems to do the same as the gulp function)
2. How does escaping the query prevent the files from being loaded multiple times?

Thanks!

**Comment by luukhartsema** [comment]
Hi Ausi, I'm a colleague of Tom. I tried a couple of things to make the css files load only once from the prolyfill.js file. Here's what I've done.

I've set the processed var to true. I was wondering why you decided to loop through the reprocess function to set the value to true? If the value needs to be true anyway? 

And I added an interval around ```preprocessSheet(sheet, step);``` 

Can you confirm this is the way to go?

**Comment by ausi** [comment]
> Do we need to implement both the Sass mixin and the gulp function or is just the Sass mixin enough (it seems to do the same as the gulp function)

One of both is enough because, as you said, they are doing the same.

> How does escaping the query prevent the files from being loaded multiple times?

If this step gets done on the server side (via Sass or PostCSS) it doesn’t have to be done on the client via JavaScript and so they don’t need to be loaded again via ajax.

> I've set the processed var to true. I was wondering why you decided to loop through the reprocess function to set the value to true? If the value needs to be true anyway?
> 
> And I added an interval around `preprocessSheet(sheet, step);` in the preprocess function.
> 
> Can you confirm this is the way to go?

You don’t have to modify the JavaScript code of the library itself, it’s only needed to tell the prolyfill that you processed the CSS on the server side as mentioned in the [Documentation](https://github.com/ausi/cq-prolyfill/blob/master/docs/postcss.md):

> To tell the prolyfill that the PostCSS plugin was used activate the `postcss` option in the [configuration](https://github.com/ausi/cq-prolyfill/blob/master/docs/).

If the stylesheets still get loaded twice, feel free to send me a link so that I can take a closer look.

**Comment by luukhartsema** [comment]
Can't it be done without using postcss?

**Comment by ausi** [comment]
Yes, by using the [Sass mixin](https://github.com/ausi/cq-prolyfill/issues/17#issuecomment-183756013), but you have to enable the `postcss` option in the [configuration](https://github.com/ausi/cq-prolyfill/blob/master/docs/).

**Comment by ausi** [comment]
@luukhartsema, @TomOffringa did you get it working?

**Comment by luukhartsema** [comment]
Yes! thanks for the help.
