### ISSUE TITLE
Sizing keywords supported?

### ISSUE THREAD

**Issue by nategreen** [ausi/cq-prolyfill#25]
Hi! Are sizing keywords like `max-content`, `min-content`, `column-width`, etc. supported in container queries? (Two questions, really: are they supported in cq-prolyfill, and, to your knowledge, are they possible/expected in the eventual CSS spec?)

**Comment by ausi** [comment]
What do you mean by supported? Can you give an example?

`width: min-content` and `width: max-content` doesn’t get recognized currently. But it should be easy to add rules for it to the [`isIntrinsicSize()`](https://github.com/ausi/cq-prolyfill/blob/3e843525cdfa2c042e0c4dcaaf58be61d5d7d089/cq-prolyfill.js#L944) function.

If `column-width` works correctly or not, depends on the use-case I think. If an element with a `column-width` gets used as the container for a query the results are probably incorrect.

**Comment by nategreen** [comment]
Yeah, what I was wondering specifically was whether I could do something like `.btn-toolbar:container(width < max-content) { /* styles that collapse buttons into a dropdown menu */ }`. Now that I think that through more, though, doing something like that would change the value of `max-content` so it wouldn't work the way I'd want it to anyway (if it didn't just blow up altogether. :smirk:).

I'm trying to get my head around how we could use element/container queries for a project I'm working on. Haven't had time to actually try cq-prolyfill out yet, just wanted to understand what the possibilities are. :) Thanks!

**Comment by ausi** [comment]
> Now that I think that through more, though, doing something like that would change the value of `max-content` so it wouldn't work the way I'd want it to anyway (if it didn't just blow up altogether. 😏).

Yeah, that could end in an endless loop, which is one of the issues this proposal/prolyfill tries to prevent.

> Haven't had time to actually try cq-prolyfill out yet, just wanted to understand what the possibilities are.

I think the most common use cases should be covered by [the demo](https://ausi.github.io/cq-prolyfill/demo/).
