### ISSUE TITLE
Support SystemJS as module loader

### ISSUE THREAD

**Issue by lmaze** [ausi/cq-prolyfill#29]
Hi there,

Here we use SystemJS (with JSPM) as module loader to load ES6 modules.
SystemJS also supports [CommonJS and AMD modules](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md) but it's not working with cq-prolyfill.

The code I have is very simple :
```
import cq from 'cq-prolyfill';

cq.reevaluate(false, function() {
	// Do something after all elements were updated
});
```
The JS file for cq-prolyfill is well loaded by the browser but the cq variable does not contain the reevaluate method. So it seems that the export is not properly done.

Do you have an idea of what could be the problem?

It would be really interesting cq-prolyfill can be loaded with SystemJS and not just with Browserify or Webpack.

**Comment by lmaze** [comment]
After some research, I think SystemJS can not properly detect the cq-prolyfill format because of the way it defines its modules.

I have a working configuration file by modifying the jspm.config.js and declaring cq-prolyfill as a global module:
```
packages: {
    "npm:cq-prolyfill@0.3.2": {
      meta: {
        'cq-prolyfill.js': {
          format: 'global',
          exports: 'cqApi'
        }
      },
	  .....
    }
}
```

However I do not know if this is the best way.

**Comment by lmaze** [comment]
And here is the configuration to declare cq-polyfill to CommonJS format with SystemJS.

In the config file :
```
packages: {
    "npm:cq-prolyfill@0.3.2": {
      meta: {
        'cq-prolyfill.js': {
          format: 'cjs'
        }
      },
      .....
    }
}
```

And in the JS file :
```
import cqFactory from 'cq-prolyfill';

const cq = cqFactory();
cq.reevaluate(false, function() {
    // Do something after all elements were updated
});
```

I hope it will help others :)
Perhaps there are also better ways of doing things.

**Comment by ausi** [comment]
Nothing to be sorry about :)
It’s great you could resolve the issue.
