### ISSUE TITLE
Minified cq-prolyfill.js file with gulp-concat doesn't work

### ISSUE THREAD

**Issue by marknotton** [ausi/cq-prolyfill#32]
So I'm using Gulp with the popular [gulp-concat](https://www.npmjs.com/package/gulp-concat) package. It allows me to compile and minify a collection of Javascript files into one minified file. 

Even if I minify and include **just** the cq-prolyfill.js file; the script doesn't work. No errors, it just doesn't work. Your own [latest release](https://github.com/ausi/cq-prolyfill/releases) cq-prolyfill.min.js works perfectly. 

Anyway, taking the uncompressed file into [JSHint](http://jshint.com/), revealed  a large amount of these warnings:

> Misleading line break before '&&'; readers may interpret this as an expression boundary.

I went through and removed those line-breaks, and gulp-concat minified it like a charm. I think it's fair to say gulp-concat has an issue with certain line-breaks. 

So, you can either make your code a little less legible and remove those line breaks... or say tough-luck to the millions of gulp-concat users. Then again, maybe I'm the only one in this situation somehow. 

Just thought I'd share my findings! Loving CQ-Prolyfill!

**Version 0.3.2 without linebreaks:** [cq-prolyfill-no-linebreaks.js.zip](https://github.com/ausi/cq-prolyfill/files/688719/cq-prolyfill-no-linebreaks.js.zip)

**Comment by ausi** [comment]
I don’t think that gulp-concat minifies js files, the documentation says it’s all about the concatenation of files.

The only problem I could think of is, if you used a non-whitespace character for the `newLine` option. Can you show the code of your usage of gulp-concat?
