### ISSUE TITLE
Is enabling all CSS properties a good idea?

### ISSUE THREAD

**Issue by ausi** [ausi/cq-prolyfill#4]
[Some](https://twitter.com/HugoGiraudel/status/653914130039107584) [reactions](https://twitter.com/zackvbrady/status/656137873603825665) [on twitter](https://twitter.com/zackvbrady/status/656139111267438592) pointed out that supporting queries for all properties may not be the best idea.

**Comment by dbox** [comment]
Maybe a plug-in style call with a sensible default set of properties?

**Comment by ausi** [comment]
The way how the prolyfill works it supports all properties. Special rules only apply for `width`, `height` and `background-color`. I could add code to ignore container queries with unsupported properties, but if someone uses a property in a container query they want support for it anyways.

Maybe it would be a good idea to add a list of supported, tested and recommended properties to the readme. What do you think would be a good set of properties? `width`, `height`, `background-color`, `text-align` and `font-size`?

**Comment by maxhoffmann** [comment]
Allowing all properties to be queried is totally legit. No one has pointed out a use case where this leads to problems yet.

The only problem I see is that component authors could add random rules like bumping the font size up if the background color is pink. Nevertheless adding a rainbow background when the parent is 428px wide would be random too. Odd design choices can't be prevented by the tool.

**Comment by lmartins** [comment]
As long as they don't affect performance if unused, I don't see an issue for non-layout properties to be available (background color, text-align, etc).

**Comment by ausi** [comment]
Thanks for your feedback! 

So I will leave it as it is now and support all properties. I added a [note to the documentation](https://github.com/ausi/cq-prolyfill/blob/master/docs/usage.md#supported-css-properties) pointing that out.

**Comment by VinSpee** [comment]
I think the most worrisome part about it is that it's syntax strays from any other in CSS by using the equal sign. I don't think there's an alternative, however. It's all about weighing the pros and cons.

**Comment by rask** [comment]
I think this is one of those situations where the problem has been made up just to have a problem. If you do not wish to use certain properties for container queries you're free to not use them.

99% of people will most probably only use the `width` and `height` properties anyway (as with regular media queries), so catering for people who *might accidentally* use `text-shadow` or something as a container query basis is wasted time.

What I would suggest is allow them all, and then add a disclaimer that your mileage may vary when using stranger properties for container querying.

And who knows, someone might come up with unique, reproducible, and awesome approaches to tricky UI problems using the stranger container query properties.

**Comment by ausi** [comment]
@rask Thanks for your feedback.

The current state is like you suggested it, I wrote in the [usage docs](https://github.com/ausi/cq-prolyfill/blob/master/docs/usage.md#supported-css-properties):

> Technically all CSS properties are supported, but that doesn’t mean you should use them all. The following properties are most useful and tested: `width`, `height`, `background-color`, `color`, `text-align`, `font-size` and [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables).

As it seems we all share the same opinion here that it is OK as it is now, I close this issue.

@VinSpee I opened an issue about the syntax differences to media queries: #8
