### ISSUE TITLE
In Safari with disabled cache container queries doesn't apply on first script load

### ISSUE THREAD

**Issue by curtdp** [ausi/cq-prolyfill#45]
In Safari 10.1.1 (12603.2.4) with disabled cache I have a page with async scripts loading after domready event and after that cq rules doesn't applies to elements untill window resize or it works when i manually call function window.cqApi.reevaluate() in browsers console.

When cache is enabled in Safari all works fine.

In Chrome and Firefox with disabled cache all works fine.

**Comment by ausi** [comment]
I was not able to reproduce the issue. Did you use the latest version for cq-prolyfill (0.3.3)?
Can you provide a link to the affected page?

**Comment by curtdp** [comment]
yes i use cq-prolyfill@0.3.3

how can i provide you a password for my private host, non public. email?

**Comment by ausi** [comment]
DM on Twitter to [@ausi](https://twitter.com/ausi) or email to martin@auswoeger.com

**Comment by curtdp** [comment]
There was a typo in selector i write a space between :container and parentheses.
With typo:
```
selector:container (conditions){}
```
Without space
```
selector:container(conditions){}
```
Removing space was solve this issue.
