### ISSUE TITLE
getContainer() delivers wrong element if element has size defined in percent

### ISSUE THREAD

**Issue by d0cm0d** [ausi/cq-prolyfill#50]
Hi there,
first of all: great project! Thanks!

Now my issue/question:
If the parent element has a width defined in percent, the getContainer() function returns a wrong element. If I am right, it should return the element itself, because the width has a fixed definition (isIntrinsicSize() returns false). So there should be the following check after the isFixedSize check:
```javascript
            else if (!isIntrinsicSize(element, prop)) {
                cache[prop] = element;
            }
```
Or am I wrong and the check is missing with a reason, and if yes, what reason?
Thanks, best regards, Pascal

**Comment by d0cm0d** [comment]
Hallo,
thank you for your comment. It made it more clear. Nevertheless, that is not the problem.
I was digging a little bit deeper and recognized, that the problem comes from the stylesheet parsing.
In my css, I include other css files. In this case, the buildStyleCacheFromRules() function fails, because the "if (rules[i].type === 1)" is false (rules[i].type is 3) and the "else if (rules[i].cssRules)" is undefined.
In this case (rules[i].type === 3), the css rules are in the object rules[i].styleSheet.cssRules.
So if we add the following case to the if, it should work:
`
else if (rules[i].type === 3 && rules[i].styleSheet.cssRules) {
    buildStyleCacheFromRules(rules[i].styleSheet.cssRules);
}
`
What do you think?

**Comment by ausi** [comment]
This sounds like the issue #49.
This was fixed in 579d039946d6924b2d5ff7dc098fbcdc45bbfc47 in the development branch and will be fixed with the next release.

**Comment by d0cm0d** [comment]
Yes, it's the same issue. I've fixed it a little bit different, because imported stylesheets can contain imported stylesheets again. I've just created a pull request, that - at least I think so - handles all cases and is very simple.
Thank you, best regards, Pascal

**Comment by ausi** [comment]
Did you test the changes from 579d039946d6924b2d5ff7dc098fbcdc45bbfc47 ?
Nested imports should work there too.

**Comment by ausi** [comment]
Ahh, sorry. I missed something. You are talking about the `buildStyleCacheFromRules()` function, not about `parseRules()`.

You are right, that needs to be fixed too. I close this issue in favor of your pull request #51.

**Comment by d0cm0d** [comment]
Hello,
I just recognized a problem with my fix with Firefox. Firefox has a bug that restricts js access to css imported with @import ("SecurityError: The operation is insecure error").
I just updated my fix and will start a new pull request.

**Comment by ausi** [comment]
Great. But you can push more commits to your existing `Fix-@import-stylesheet-parsing` branch. This way you don’t have to create a new pull request.
