### ISSUE TITLE
Don't work in Chrome 112

### ISSUE THREAD

**Issue by hrynevychroman** [ausi/cq-prolyfill#60]
Stopped working in Chrome 112, issue may be nesting support out of the box
Chrome 111
![image](https://user-images.githubusercontent.com/82209198/230742998-1936a0ed-6477-48de-a5bc-3cae4ec733ab.png)
Chrome 112
![image](https://user-images.githubusercontent.com/82209198/230743030-3dc59c06-619e-48ef-9c0d-166d50a25f69.png)

**Comment by digitalcraft** [comment]
Yeah, so looks like you need to check for length here. https://github.com/ausi/cq-prolyfill/blob/master/cq-prolyfill.js#L562

https://chromestatus.com/feature/5800613594529792

**Comment by hrynevychroman** [comment]
Yeah, change if statement to this, and it's worked, thanks)
if (rule.cssRules && rule.cssRules.length)
