### ISSUE TITLE
Should the syntax be changed (again) to match CSS Media Queries Level 4

### ISSUE THREAD

**Issue by ausi** [ausi/cq-prolyfill#8]
The [Media Queries Level 4 draft](https://drafts.csswg.org/mediaqueries4/#mq-features) allows a slightly different syntax for media features than cq-prolyfill. Using the same syntax as media queries would be more consistent and thus easier to reason about for CSS authors.

The current syntax would still be valid for simple queries e.g. `width > 100px`, but more variants would be possible like `min-width: 100px`, `text-align: right` or even `100px < width`.

Queries with two comparisons would change from `width > 100px < 200px` to the range syntax of the specification `100px < width < 200px` or `200px > width > 100px`.

The color filters would be changed to a suffix so `color lightness <= 20%` gets `color-lightness <= 20%` or `max-color-lightness: 20%`.

The biggest difference is that media queries don’t allow the not-equal (`!=`) comparision, so `:container(text-align != right)` would become `:not(:container(text-align = right))` or `:not(:container(text-align: right))`.

Are the benefits of this enough to justify another change to the syntax of cq-prolyfill? (+1 or -1 comments are welcome too :)

**Comment by maxhoffmann** [comment]
> Using the same syntax as media queries would be more consistent and thus easier to reason about for CSS authors.

I agree the CQ syntax should be as close as possible to the MQ syntax. Even identical if possible in my opinion.

**Comment by MarcusJT** [comment]
+1 for following the MQ syntax

**Comment by tregusti** [comment]
So, not many responses here, but so far the consensus is to change the syntax. Any thoughts on going forward?

**Comment by ausi** [comment]
I think you are right, we should change the syntax as suggested.

> Any thoughts on going forward?

As soon as I’ve got time, I will work on it :)

**Comment by ausi** [comment]
Implemented in version [0.4.0](https://github.com/ausi/cq-prolyfill/releases/tag/v0.4.0).
